// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode_audio`, `key_to_string`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AudioData`

Future<AnalysisResult> analyze({required String pathStr}) =>
    RustLib.instance.api.crateApiAudioAnalysisAnalyze(pathStr: pathStr);

class AnalysisResult {
  final double bpm;
  final double bpmConfidence;
  final String key;
  final double keyConfidence;

  const AnalysisResult({
    required this.bpm,
    required this.bpmConfidence,
    required this.key,
    required this.keyConfidence,
  });

  @override
  int get hashCode =>
      bpm.hashCode ^
      bpmConfidence.hashCode ^
      key.hashCode ^
      keyConfidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnalysisResult &&
          runtimeType == other.runtimeType &&
          bpm == other.bpm &&
          bpmConfidence == other.bpmConfidence &&
          key == other.key &&
          keyConfidence == other.keyConfidence;
}
