// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<AudioData> decodeAudio({required String pathStr}) =>
    RustLib.instance.api.crateApiAudioAnalysisDecodeAudio(pathStr: pathStr);

class AudioData {
  final Float32List samples;
  final int sampleRate;

  const AudioData({required this.samples, required this.sampleRate});

  @override
  int get hashCode => samples.hashCode ^ sampleRate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioData &&
          runtimeType == other.runtimeType &&
          samples == other.samples &&
          sampleRate == other.sampleRate;
}
